[package]
name = "generic-intent-type"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = "0.15.1"
ckb-hash = { version = "0.112.0", default-features = false, features = [
    "ckb-contract",
] }
molecule = { version = "0.7.5", default-features = false }

